import { ref } from 'vue'

export const ENCOURAGEMENT_MESSAGES = [
  "You're here, and that counts for something. 💙",
  "Starting is the hardest part. You've already done that.",
  "There's no right way to do this. Your way is fine.",
  'Even tiny progress moves things forward.',
  "You don't have to do everything. Just one small thing.",
  'Rest is also part of getting things done.',
  "You're doing better than you think you are.",
  "It's okay if this takes longer than you expected.",
  'Being here is enough. The rest will follow when it can.',
  'Your brain works differently, not worse.',
  'This task is smaller than it feels right now.',
  "You've got through hard things before. This is one more.",
  "You don't have to feel motivated to make a start.",
  'Slow and wobbly still counts as moving forward.',
  "You're allowed to take breaks. Lots of them.",
  'One thing at a time. Just this one.',
  "It doesn't have to be perfect. It just has to happen.",
  'The fact that you opened this means something.',
  "Your energy is limited. It's okay to spend it wisely.",
  "You're not lazy. You're working within real limits.",
  'Starting for two minutes counts.',
  'Give yourself credit for the invisible effort.',
  "Things don't have to feel hard to be worth doing.",
  'Even resting can be productive.',
  "Today's version of you is doing the best they can.",
  "Demand avoidance is real. You're navigating it.",
  'Being aware of what you need is a strength, not a flaw.',
  "One less thing on the list. That's the whole goal.",
  'You made it to today. That matters.',
  "The pressure you feel isn't the truth about what's possible.",
  "Progress looks different every day. That's okay.",
  "You're not behind. You're exactly where you are.",
  'What would feel like the smallest possible step right now?',
  "You don't owe anyone a perfect performance.",
  'Your nervous system is doing a lot right now. Be gentle with it.',
  'Doing something small is still doing something.',
  'Things in progress count as things happening.',
  "You're allowed to find this hard.",
  "It's okay to switch tasks when one feels stuck.",
  'Momentum can come after starting, not before.',
  "You don't have to be at 100% to make some progress.",
  "Existing today took effort. That's worth noticing.",
  "This is hard because it's genuinely hard, not because of you.",
  "The mental load you're carrying is real and heavy.",
  'Small is still real. A little is still something.',
  "You're not failing. You're managing.",
  'Let this be low stakes. It can be.',
  "You've done things like this before, even when it felt impossible.",
  "It's okay to do this imperfectly and move on.",
  'Your pace is your pace. There is no correct speed.',
  "Notice what you've already done today, not just what's left.",
  'You deserve encouragement just for trying.',
  'Working with your brain, not against it, is the smart move.',
  "If it feels too big, make it smaller. There's no rule against that.",
  'You are not a machine. You are a person. Act accordingly.',
  'A messy start is still a start.',
  'You have more capacity than your anxiety says you do.',
  'This task exists to serve you, not the other way around.',
  "Being gentle with yourself isn't giving up. It's strategy.",
  'You can come back to the hard bits later.',
  "It's okay to ask for what you need to get started.",
  "Every task you finish was once a task you hadn't started.",
  "You're doing something today. That's not nothing.",
  "Sometimes 'good enough' is the wisest choice.",
  "You don't need to earn a rest. Rest is already yours.",
  'Noticing resistance is not the same as failing.',
  "Your efforts have value even when they're hard to see.",
  'You are more than your to-do list.',
  'The task can wait for you to be ready enough.',
  'Even if this took longer than expected, you still did it.',
  'You are not a burden for needing things structured differently.',
  'Let this be just one thing. Not everything.',
  "It's okay to take the easy route. Easier is still done.",
  'The goal is not perfection. The goal is movement.',
  'Right now, at this moment, you are okay.',
  'You get to decide what counts as success today.',
  "Your worth doesn't go up or down based on task completion.",
  "If you've been sitting with this, that's not wasted time.",
  'Working around your brain takes skill. You have it.',
  "A plan you'll actually do beats a perfect plan you won't.",
  "You're not expected to be at full capacity all the time.",
  "The energy it takes to get started is real. You're spending it.",
  "You can pause without stopping. They're different things.",
  "Your best looks different on different days. Today's version counts.",
  "It's okay to outsmart the resistance instead of fighting it.",
  "You're building something, even on days that don't feel like it.",
  "Showing up is a choice. You made it. That's real.",
  'Not everything needs to be done today. Some things can wait.',
  "You're not alone in finding this kind of thing hard.",
  'Gentle persistence is still persistence.',
  'Done is better than perfect. Done is actually better.',
  "The moment you're in right now is manageable.",
  'Trust yourself to know what you can handle today.',
  "You've navigated hard things quietly. This is another one you'll get through.",
  'Being aware of your limits is wisdom, not weakness.',
  'Start anywhere. Starting anywhere is better than not starting.',
  'Even a small win today is worth noticing.',
  "You are doing this in the way that works for you. That's valid.",
  "There's no shame in needing a different approach.",
  'Whatever you manage today is enough.',
]

export const ENERGY_MESSAGES = {
  tiny: [
    'Tiny energy is still energy. It counts.',
    'Being here with almost nothing left takes real courage.',
    'You don\'t have to do much. Just a little is enough today.',
    'Rest is valid work too.',
    'Tiny steps are still forward.',
    'You showed up. That\'s the whole thing.',
    'Low energy days happen. You\'re not broken.',
    'Just being here right now is something.',
    'It\'s okay to do the very smallest thing today.',
    'You\'re allowed to go slowly. As slowly as you need.',
    'Even a tiny amount of effort matters.',
    'Be kind to yourself — you\'re running on low.',
    'The fact that you\'re here at all is worth noticing.',
    'Small doesn\'t mean unimportant.',
    'You don\'t need to be at full capacity to do something good.',
    'One tiny thing done is still one thing done.',
    'Give yourself permission to take it very easy today.',
    'Whatever you manage will be enough.',
    'Your energy is limited today, and that\'s okay.',
    'Gentle is the right speed right now.',
  ],
  small: [
    'Small energy is still something to work with.',
    'You don\'t have to push hard today — just move at your own pace.',
    'It\'s okay to keep it simple. Simple gets things done.',
    'A little goes further than it feels like it will.',
    'Be easy on yourself — you\'re working within real limits.',
    'Small is a perfectly fine place to start from.',
    'You can do things even when you don\'t feel great.',
    'This is enough. You are enough.',
    'Pick the smallest task and let that be your win today.',
    'You\'re doing this on less energy. That takes more strength, not less.',
    'It\'s okay to aim for small things today.',
    'Progress doesn\'t have to be big to be real.',
    'You\'ve got a little — let\'s use it wisely.',
    'Low energy days need low-pressure tasks. You\'ve got this.',
    'Something small done today is still something done.',
    'Working at a slower pace is still working.',
    'Be gentle with your expectations today.',
    'Every little bit helps, even when it doesn\'t feel like it.',
    'You\'re managing. That\'s not nothing.',
    'Small and steady is still moving forward.',
  ],
  medium: [
    'Medium energy? That\'s a good place to work from.',
    'You\'ve got a decent amount to work with today.',
    'Feeling okay is worth using well.',
    'Steady days are the ones where real progress happens.',
    'You\'re in a good spot. Let\'s make the most of it.',
    'Moderate energy is more than enough for meaningful work.',
    'Not every day needs to be peak performance. Today sounds manageable.',
    'A steady pace will get you there.',
    'You\'re in the zone where things actually get done.',
    'Middle ground energy is solid ground.',
    'Today sounds workable. That\'s great.',
    'You have enough to make a real dent in things today.',
    'Consistent and steady wins the race.',
    'A good day for ticking things off the list.',
    'You\'re well-placed to make some real progress.',
    'Feeling okay is underrated. Use it.',
    'Medium days are the backbone of getting things done.',
    'You\'re set up well for today. Go for it.',
    'This is a great energy level to work at your own rhythm.',
    'Solid footing today — you\'ve got this.',
  ],
  large: [
    'You\'ve got loads to work with today — make the most of it!',
    'High energy day! Time to tackle the things you\'ve been putting off.',
    'When you feel like this, big things get done.',
    'Lots of energy today — this is your moment.',
    'You\'re firing on all cylinders. Use it well.',
    'High energy is a gift. Spend it on something that matters.',
    'Today feels like a day for big moves.',
    'You\'re in a great headspace. Let\'s go.',
    'Full capacity? That\'s rare. Don\'t waste it.',
    'This is the energy to tackle your hardest tasks.',
    'You\'ve got more than enough today. Let that feel good.',
    'High energy days are precious — use this one well.',
    'You\'re ready for the big stuff today.',
    'Everything feels possible on days like this.',
    'Strong energy day — trust it and run with it.',
    'Today\'s the day for the tasks you\'ve been avoiding.',
    'You\'re in a powerful place right now.',
    'High capacity, high possibility. Go get it.',
    'This is your peak — enjoy it and use it.',
    'Full energy means anything is on the table today.',
  ],
}

const encouragement = ref(null)
let timer = null

export function useEncouragement() {
  function showEncouragement() {
    const message =
      ENCOURAGEMENT_MESSAGES[Math.floor(Math.random() * ENCOURAGEMENT_MESSAGES.length)]
    clearTimeout(timer)
    encouragement.value = message
    timer = setTimeout(() => {
      encouragement.value = null
    }, 5000)
  }

  function showEnergyEncouragement(levelId) {
    const messages = ENERGY_MESSAGES[levelId]
    if (!messages) return
    const message = messages[Math.floor(Math.random() * messages.length)]
    clearTimeout(timer)
    encouragement.value = message
    timer = setTimeout(() => {
      encouragement.value = null
    }, 5000)
  }

  function dismissEncouragement() {
    clearTimeout(timer)
    encouragement.value = null
  }

  return { encouragement, showEncouragement, showEnergyEncouragement, dismissEncouragement }
}
